/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/app': RouteRecordInfo<
      '/app',
      '/app',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/install': RouteRecordInfo<
      '/install',
      '/install',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/widgets/background-error-handler': RouteRecordInfo<
      '/widgets/background-error-handler',
      '/widgets/background-error-handler',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/widgets/background-handler': RouteRecordInfo<
      '/widgets/background-handler',
      '/widgets/background-handler',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/widgets/dynamic-page': RouteRecordInfo<
      '/widgets/dynamic-page',
      '/widgets/dynamic-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/app.vue': {
      routes:
        | '/app'
      views:
        | never
    }
    'src/pages/install.vue': {
      routes:
        | '/install'
      views:
        | never
    }
    'src/pages/widgets/background-error-handler.vue': {
      routes:
        | '/widgets/background-error-handler'
      views:
        | never
    }
    'src/pages/widgets/background-handler.vue': {
      routes:
        | '/widgets/background-handler'
      views:
        | never
    }
    'src/pages/widgets/dynamic-page.vue': {
      routes:
        | '/widgets/dynamic-page'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
